"""initial_schema

Revision ID: 90c6c415fb6a
Revises: 
Create Date: 2026-08-07 19:18:19.953378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90c6c415fb6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_actor'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_entity'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_restaurant'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_platform_role'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('idx_restaurant_members_restaurant'), table_name='restaurant_members')
    op.drop_index(op.f('idx_restaurant_members_role'), table_name='restaurant_members')
    op.drop_index(op.f('idx_restaurant_members_status'), table_name='restaurant_members')
    op.drop_index(op.f('idx_restaurant_members_user'), table_name='restaurant_members')
    op.drop_table('restaurant_members')
    op.drop_index(op.f('idx_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_index(op.f('idx_refresh_tokens_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('idx_refresh_tokens_restaurant'), table_name='refresh_tokens')
    op.drop_index(op.f('idx_refresh_tokens_user'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('idx_restaurants_created_by'), table_name='restaurants')
    op.drop_index(op.f('idx_restaurants_owner'), table_name='restaurants')
    op.drop_index(op.f('idx_restaurants_status'), table_name='restaurants')
    op.drop_index(op.f('idx_restaurants_updated_by'), table_name='restaurants')
    op.drop_table('restaurants')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('cuisine_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=100), server_default=sa.text("'UTC'::character varying"), autoincrement=False, nullable=False),
    sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('lifecycle_status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('supported_languages', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("ARRAY['en'::text]"), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.CheckConstraint("lifecycle_status::text = ANY (ARRAY['draft'::character varying, 'active'::character varying, 'suspended'::character varying, 'archived'::character varying]::text[])", name='chk_restaurant_lifecycle_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_restaurants_created_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='fk_restaurants_owner', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_restaurants_updated_by', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='restaurants_pkey'),
    comment='Each record represents one tenant (restaurant).',
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_restaurants_updated_by'), 'restaurants', ['updated_by'], unique=False)
    op.create_index(op.f('idx_restaurants_status'), 'restaurants', ['lifecycle_status'], unique=False)
    op.create_index(op.f('idx_restaurants_owner'), 'restaurants', ['owner_id'], unique=False)
    op.create_index(op.f('idx_restaurants_created_by'), 'restaurants', ['created_by'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('restaurant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('device_info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_refresh_tokens_restaurant'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_tokens_pkey')),
    comment='Stores hashed JWT refresh tokens for authenticated sessions.'
    )
    op.create_index(op.f('idx_refresh_tokens_user'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('idx_refresh_tokens_restaurant'), 'refresh_tokens', ['restaurant_id'], unique=False)
    op.create_index(op.f('idx_refresh_tokens_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('idx_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_table('restaurant_members',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('restaurant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('invited_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.CheckConstraint("role::text = ANY (ARRAY['owner'::character varying, 'manager'::character varying, 'staff'::character varying]::text[])", name=op.f('chk_restaurant_member_role')),
    sa.CheckConstraint("status::text = ANY (ARRAY['active'::character varying, 'invited'::character varying, 'suspended'::character varying, 'removed'::character varying]::text[])", name=op.f('chk_restaurant_member_status')),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_restaurant_members_invited_by'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_restaurant_members_restaurant'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_restaurant_members_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('restaurant_members_pkey')),
    sa.UniqueConstraint('restaurant_id', 'user_id', name=op.f('uq_restaurant_member'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='Maps users to restaurants with restaurant-specific roles.'
    )
    op.create_index(op.f('idx_restaurant_members_user'), 'restaurant_members', ['user_id'], unique=False)
    op.create_index(op.f('idx_restaurant_members_status'), 'restaurant_members', ['status'], unique=False)
    op.create_index(op.f('idx_restaurant_members_role'), 'restaurant_members', ['role'], unique=False)
    op.create_index(op.f('idx_restaurant_members_restaurant'), 'restaurant_members', ['restaurant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('email', postgresql.CITEXT(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('platform_role', sa.VARCHAR(length=20), server_default=sa.text("'user'::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_email_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("platform_role::text = ANY (ARRAY['user'::character varying, 'support'::character varying, 'admin'::character varying, 'super_admin'::character varying]::text[])", name='chk_users_platform_role'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='uq_users_email', postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='System users. Restaurant-specific permissions are managed via restaurant_members.',
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_users_platform_role'), 'users', ['platform_role'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('restaurant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_audit_logs_restaurant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey')),
    comment='Immutable audit trail for tenant activities.'
    )
    op.create_index(op.f('idx_audit_logs_restaurant'), 'audit_logs', ['restaurant_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_entity'), 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_created_at'), 'audit_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_audit_logs_actor'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    # ### end Alembic commands ###
